# Generated by Django 5.2.10 on 2026-01-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_commentreport_postreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreport',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postreport',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
