# Generated by Django 5.2.10 on 2026-01-24 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Standard Text'), ('confession', 'Confession'), ('question', 'Question'), ('rant', 'Rant'), ('shoutout', 'Shoutout'), ('event', 'Event')], default='text', max_length=20),
        ),
    ]
