# Generated by Django 5.2.10 on 2026-01-17 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communitymembership'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name'], name='communities_name_3031a9_idx'),
        ),
    ]
